services:
  - type: web
    name: velora-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: TMDB_ACCESS_TOKEN
        value: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYjY0ZDZhOTE4YzA5NjVjMTBiYWVhZDFhNTdlMWEzNyIsIm5iZiI6MTc3NDkyMjA3OC43MjgsInN1YiI6IjY5Y2IyOTVlNmM1MWQ4NGFmOWNhM2JiNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.vxX1SUw4SjVECMG7oSmpSAC3GdeiBpVerEHCjjyczOQ"
    healthCheckPath: /api/v1/health
    autoDeploy: true
